Tsf 3930 error handling
navikt/k9-legeerklaering-on-fhir pull request #267
Opened 2024-01-31 14:35 UTC by josstn

Legger til generell toppnivå feilsider som vil vise feilmelding til bruker viss det oppstår feil som ikkje blir fanga lenger nede i komponenthierarkiet.

2024-02-05 07:15 UTC, leoervik requested changes
Litt blanding av Norsk og Engelsk. Bør også splitte PR inn i relevant arbeid.
Ellers ser det bra ut! 👍

2024-02-05 07:15 UTC, leoervik commented on src/app/components/feedback/FeedbackEmail.tsx
> +export const defaultSubjectSuggestion = "Feedback legeerklæring pilot"
~Feedback~ Tilbakemelding

2024-02-05 07:15 UTC, leoervik commented on src/app/components/feedback/FeedbackEmail.tsx
Denne bør være i egen PR for å ikke blande error handling med noe annet.

2024-02-05 10:41 UTC, josstn commented on src/app/components/feedback/FeedbackEmail.tsx
Den er med som ein del av denne PR fordi FeedbackEmail er brukt på feilmeldingssidene, så brukaren veit kvar hen kan sende feilmelding. Er ikkje det naturleg å ha den med som ein del av denne PR då?

Kjem forøvrig ein ny PR som har med tilbakemeldingsside å gjere så snart denne er merged 🙂

2024-02-06 09:05 UTC, leoervik approved these changes

2024-02-08 13:29 UTC, merged